"""
analysis.py
Analyses the results.csv file generated by testing.py

This script works through the pairwise test results in stages, each one
asking a different question about how well ChroCompare's suggestions
perform compared to a naive baseline (naive_model2 from testing.py, i.e.
"pick the column with the largest predicted separation among those where
both predictions fall in the required range"):

  1. How often does ChroCompare's suggested column/order agree with the
     true best column/order, and with the naive baseline's suggestion?
  2. Of the pairs where ChroCompare and the naive baseline *disagree*,
     how often is each one actually right?
  3. Is the predicted separation probability calibrated, i.e. of the pairs
     predicted to separate with probability ~p, do about p of them
     actually separate? (ROC AUC, then two binned "reliability" views:
     one for just the suggested column, one pooling all columns.)
  4. Does ChroCompare's suggestion get better as more columns are capable
     of separating a given pair at all?

Functions:
  column_match(col1, col2, first1, first2): returns 1 if two column
     choices agree and they agree on elution order, else 0.
  in_range(val1, val2): checks if both values are in required range.
  good_sep(val1, val2): checks if two retention factors meet the
     separation criteria (both in range, and separated by at least
     REQUIRED_SEPARATION); also returns which one elutes first.
  col_good_sep(x, col): as good_sep, but reads the true retention factors
     for `col` from a results row `x`, and only counts the pair as
     separated if the elution order was also predicted correctly.
  col_good_sep2(x, col): as col_good_sep, but does not require the
     elution order to have been predicted correctly.
  true_to_val(boo): converts a bool to 1/0 (needed because pandas
     .mean() on a bool column doesn't always behave as we want when built
     up via .apply()).
  same_order(x, col): checks whether the predicted and true elution order
     agree for `col` in a results row `x`.
  count_seps(x, cols): counts, for a results row `x`, how many of `cols`
     both separate the pair (per col_good_sep) and get the order right.
"""
import pandas as pd
import numpy as np
from tqdm import tqdm
from sklearn.metrics import roc_auc_score

REQUIRED_RANGE = [0.05, 0.95]
REQUIRED_SEPARATION = 0.1

df = pd.read_csv('results_5.csv')
columns = pd.read_csv('columns.csv')
cols = list(columns['name'])
df.drop_duplicates(inplace=True)

def column_match(col1, col2, first1, first2):
    """Returns 1 if both the chosen column and the elution order agree.

    Used to compare two "column choice" strategies (e.g. ChroCompare's
    suggestion vs. the naive baseline, or either vs. the true best column)
    row by row.
    """
    if col1 == col2 and first1 == first2:
        return 1
    return 0

# Stage 1: how often do the three strategies agree with each other?
# 'true_naive2'/'true_2_first' is the naive strategy applied to the true
# retention factors, i.e. it stands in here for "the actual best column".
df['predicted_matched_true'] = df.apply(lambda x: column_match(x.col_choice, x.true_naive2, x.choice_first, x.true_2_first), axis = 1)
df['naive_matched_true'] = df.apply(lambda x: column_match(x.pred_naive2, x.true_naive2, x.pred_2_first, x.true_2_first), axis =1)
df['predicted_matched_naive'] = df.apply(lambda x: column_match(x.col_choice, x.pred_naive2, x.choice_first, x.pred_2_first), axis=1)

print('')
print(df[['predicted_matched_true','naive_matched_true','predicted_matched_naive']].describe())

def in_range(val1, val2):
    """Checks if both values are in required range"""
    return (REQUIRED_RANGE[0] <= val1 <= REQUIRED_RANGE[1] and
            REQUIRED_RANGE[0] <= val2 <= REQUIRED_RANGE[1])

def good_sep(val1, val2):
    """Checks if values fulfill separation criteria"""
    if in_range(val1, val2) and abs(val1 - val2) >= REQUIRED_SEPARATION:
        return True, val1 > val2
    return False, val1 > val2

def col_good_sep(x, col):
    """As good_sep, but pulls the true retention factors for `col` out of
    a results row `x`. Only counts it as separated if the predicted
    elution order (from `col`_pred1/2) also matches the true order"""
    true1 = x[col+'_true1']
    true2 = x[col+'_true2']
    first_pred = x[col+'_pred1'] > x[col+'_pred2']
    separated, first_true = good_sep(true1,true2)
    if first_true == first_pred:
        return separated
    return False

def true_to_val(boo):
    """Converts a bool to 1/0, so it can be averaged with pandas .mean()."""
    if boo:
        return 1
    return 0

# --- Stage 2: overall separation rate for ChroCompare vs. the naive baseline ---
df['naive2_separated'] = df.apply(lambda x: col_good_sep(x, x.pred_naive2), axis=1)
df['choice_val'] = df['choice_sep'].apply(true_to_val)
df['naive_val'] = df['naive2_separated'].apply(true_to_val)
# choice_prob: the predicted separation probability for whichever column
# ChroCompare actually suggested (col_choice)
df['choice_prob'] = df.apply(lambda x: x[x.col_choice+'_sep'], axis=1)

print('Proportions for ChroCompare and naive choices and the predicted probability:')
print(df[['choice_val','naive_val','choice_prob']].describe())

# Restricting to the pairs where ChroCompare and the naive baseline picked
# a *different* column isolates the cases that actually test whether
# ChroCompare's probability model is adding anything over the naive rule.
print('The proportions when the suggested and naive choices match:')
df2 = df.drop(df[df.predicted_matched_naive == 1].index)
print(df2[['choice_val','naive_val','choice_prob']].describe())

print('ROC AUC:')
print(roc_auc_score(list(df['choice_val']),list(df['choice_prob'])))


# --- Stage 3a: ROC-style sweep, used by AUC_curve.py to plot the curve ---
# This section can be slow to compute, if rerunning this script it is recommended to comment it out
positives = df.drop(df[df.choice_val == 0].index)
negatives = df.drop(df[df.choice_val == 1].index)

arr = np.array((0,1,1))

print('Generating ROC data')
for i in tqdm(range(500)):
    threshold = (i+1)/500
    # At this threshold: what fraction of pairs that did separate would
    # have been correctly flagged (true positive rate), and what fraction
    # of pairs that didn't separate would have been incorrectly flagged
    # (false positive rate)?
    positives['true_positives'] = positives.apply(lambda x: true_to_val(x.choice_prob > threshold), axis=1)
    negatives['false_positives'] = negatives.apply(lambda x: true_to_val(x.choice_prob > threshold), axis=1)

    arr = np.vstack((arr, (threshold, positives['true_positives'].mean(), negatives['false_positives'].mean())))


auc = pd.DataFrame({'threshold':arr[:,0], 'TPR':arr[:,1], 'FPR':arr[:,2]})
print('Saving ROC AUC curve data to: AUC_data.csv')
auc.to_csv('AUC_data.csv')

# Precompute, for every column (not just the one ChroCompare suggested),
# whether that column would have separated the pair -- needed for the
# "all columns" reliability check in Stage 3c below.
for col in cols:
    df[col+'_sep_val'] = df.apply(lambda x: true_to_val(col_good_sep(x, col)), axis=1)

# --- Stage 3b: calibration/reliability check, suggested column only ---
# Bin pairs by their predicted separation probability (0-1%, 1-2%, ...)
# and compare the predicted probability in each bin to the observed
# fraction that actually separated. A well-calibrated model should trace
# close to the y=x line when plotted (see percentage_plot.py).
arr = []

for i in range(100):
    selection = df.drop(df[(i/100 > df.choice_prob) | (df.choice_prob >= (i+1)/100)].index)
    # Skip bins with too few pairs to give a meaningful average.
    if selection['choice_prob'].size >= 30:
        arr.append([i/100, selection['choice_val'].mean(), selection['choice_prob'].size])


arr = np.array(arr)
percentages = pd.DataFrame({'percentage_pred':arr[:,0],'percentage_true':arr[:,1],'percentage_population':arr[:,2]})
print('Saving percentile data for suggested method to: percentage_data_choice.csv')
percentages.to_csv('percentage_data_choice_5.csv')

# --- Stage 3c: same reliability check, but pooling every column together ---
# (not just whichever one was suggested) -- checks that the probability
# model is calibrated in general, not just for the columns ChroCompare
# happens to pick.
arr = []
sum = 0

for i in range(100):
    #arr = []
    #sum = 0
    vals = []
    for col in cols:
        selection = df.drop(df[(i/100 > df[col+'_sep']) | (df[col+'_sep'] >= (i+1)/100)].index)
        vals += list(selection[col+'_sep_val'])
        sum += selection[col+'_sep_val'].size
    if len(vals) >= 100:
        arr.append([i/100, np.mean(np.array(vals)),len(vals)])

arr = np.array(arr)

percentages = pd.DataFrame({'percentage_pred':arr[:,0],'percentage_true':arr[:,1],'percentage_population':arr[:,2]})
print('Saving percentile data for all methods to: percentage_data_all.csv')
percentages.to_csv('percentage_data_all.csv')

# --- Stage 4: does the suggestion quality depend on how many columns ---
# --- could separate the pair at all? ---

def same_order(x, col):
    """Checks whether the predicted and true elution order agree for
    `col` in a results row `x`."""
    true1 = x[col+'_true1']
    true2 = x[col+'_true2']
    pred1 = x[col+'_pred1']
    pred2 = x[col+'_pred2']
    return (true1 > true2) == (pred1 > pred2)

def count_seps(x, cols):
    """Counts how many of `cols` both separate the pair described by
    results row `x` (per col_good_sep) and have the correct predicted
    elution order. Used as a proxy for "how easy was this pair to
    separate at all", to check whether ChroCompare's suggestions do
    better on easier pairs."""
    count = 0
    for col in cols:
        if x[col+'_sep_val'] == 1 and same_order(x, col):
            count += 1
    return count

df['sep_count'] = df.apply(lambda x: count_seps(x, cols), axis=1)

print('Number of separable columns, Number of pairs, Proportion of successful suggestions, Mean predicted probability')
for i in range(len(cols)+1):
    selection = df.drop(df[df.sep_count != int(i)].index)
    print(str(i)+', '+str(selection['choice_val'].size)+', '+str(selection['choice_val'].mean())+', '+str(selection['choice_prob'].mean()))
