"""
AUC_curve.py

Plots the receiver operating characteristic curve
from the AUC_data.csv generated by analysis.py
"""
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

plt.rcParams["font.family"] = "Nimbus Sans"
plt.rcParams['font.size'] = 18
plt.rcParams['figure.figsize'] = (8,6)

df = pd.read_csv('AUC_data.csv')
FILE_OUT = './Plots/AUC_plot.png'

TPR = np.array(df['TPR'])
FPR = np.array(df['FPR'])

AUC = 0

for i in range(len(FPR)-1):
    AUC += TPR[i+1]*(FPR[i]-FPR[i+1])

print(AUC)

plt.step(FPR, TPR)
plt.plot([0,1],[0,1], linestyle='dashed', color='grey')
plt.xlabel('False Positive Rate')
plt.ylabel('True Postive Rate')
plt.title('Receiver Operating Characteristic')
plt.text(0.05,0.95, 'AUC='+str(round(AUC,4)))

print('Saving plot to: '+FILE_OUT)
plt.savefig(FILE_OUT)
