"""
generate_calibration.py
Generates the models and calibration distributions for the ChroCompare algorithm
and saves in /Models/ and /CalibrationData/ folders respectively. Requires the list
and lengths of columns specified in COLUMN_FILE (here columns.csv). DATA_FILE should
include fingerprints (as generated by generate_fingerprints) and retention times
(with each chromatographic column being a separate column in the csv).

Functions:
  list_from_str(list): splits the saved string from the csv into the required list
"""

import pandas as pd
import numpy as np
import cloudpickle

from sklearn.ensemble import RandomForestRegressor as RandomForest
from sklearn.model_selection import train_test_split

from scipy.stats import gaussian_kde

COLUMN_FILE = 'columns.csv'
DATA_FILE = ''

def list_from_str(list_in):
    """Splits string into required list of floats"""
    result = list_in.strip('[]').split(', ')
    result = [float(item) for item in result]
    return result

print('Getting data')
cols = pd.read_csv(COLUMN_FILE)
df = pd.read_csv(DATA_FILE)

for index, dictio in cols.iterrows():
    col, length = dictio[['name', 'length']]
    reduced_df = df.dropna(subset=[col,'Fingerprint'])
    x = np.array(list(reduced_df['Fingerprint'].apply(list_from_str)))
    y = np.array(reduced_df[col])/length

    y_trues = []
    y_preds = []

    #generating the calibration data
    for i in range(50):
        print(col+' round '+str(i+1))
        x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

        rf = RandomForest()
        rf.fit(x_train, y_train)
        y_preds = np.append(y_preds, rf.predict(x_test))
        y_trues = np.append(y_trues, y_test)

    print('Generating kde')
    kde = gaussian_kde(np.array([y_trues, y_preds]))

    n = 1000
    cdf = np.zeros((n,n))
    pdf = np.zeros((n,n))
    cdf[:,0] = 1

    #looping through to populate the matrices
    for i in range(n):
        x_s = np.linspace(0+1/(2*n),1-1/(2*n),n)
        y_s = kde.evaluate(np.vstack([x_s,np.full(n,i/n)]))
        l = np.sum(y_s)/n
        pdf[i,:] = y_s/l
        for j in range(1,n):
            cdf[i,j] = cdf[i,j-1] - pdf[i,j-1]/n

    #saves look up matrices
    out_file = './CalibrationData/'+col+'_CDF.cp.pkl'
    with open(out_file, 'wb') as f:
        cloudpickle.dump(cdf, f)

    out_file = './CalibrationData/'+col+'_PDF.cp.pkl'
    with open(out_file, 'wb') as f:
        cloudpickle.dump(pdf, f)

    out_file = './CalibrationData/'+col+'_kde.cp.pkl'
    with open(out_file, 'wb') as f:
        cloudpickle.dump(kde, f)

    #retains on full data set and saves model
    rf = RandomForest()
    rf.fit(x, y)
    out_file = './Models/'+col+'_model.cp.pkl'
    with open(out_file, 'wb') as f:
        cloudpickle.dump(rf, f)
