"""
percentage_plot.py

Plots the observed proportion of separation pairs
against the predicted probability and a histogram
of the prediction distribution.
Requires a percentage_data.csv generated by
analysis.py
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score

df = pd.read_csv('percentage_data_choice.csv')
FILE_OUT = './Plots/percentage_choice_plot.png'

true_percentage = np.array(df['percentage_true'])
pred_percentage = np.array(df['percentage_pred'])
frequencies = np.array(df['percentage_population'])

fig, ax1 = plt.subplots()

ax2 = ax1.twinx()

ax2.bar(pred_percentage, frequencies, width=0.01, alpha=0.5)

ax1.step(pred_percentage, true_percentage)
ax1.plot([0,1],[0,1], linestyle='dashed', color='green')
ax1.set_xlabel('Predicted Probability')
ax1.set_ylabel('Observed Proportion')
ax2.set_ylabel('Frequency')
plt.title('Proportion of Pairs With 10% Separation Versus Predicted Probability\nFor Suggested Method')

fig.tight_layout()
Print('Saving plot to: '+FILE_OUT)
plt.savefig(FILE_OUT)

print(r2_score(true_percentage, pred_percentage))
